logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
#    org.eclipse.jetty: WARN
    org.eclipse.jetty.server.Server: INFO
    au.com.privitar: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/vrms-app.log
      archive: true
      archivedLogFilenamePattern: /var/log/vrms-app-%i.log
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"

mongo:
  host: localhost
  port: 39999
  db: iflit
  user: ajt001
  password: iflitpwd
